all:
  hosts:
    pi:
      ansible_host: "{{ lookup('env', 'PI_HOST') | default('192.168.0.42') }}"
      ansible_user: "{{ lookup('env', 'PI_USER') | default('ronnel') }}"
      ansible_password: "{{ lookup('env', 'PI_PASS') | default('') }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_python_interpreter: /usr/bin/python3
      ansible_become: true
      ansible_become_method: sudo